### ISSUE TITLE
命令行创建失败

### ISSUE THREAD

**Issue by biwankaifa** [hyperf/resource#1]
```
php bin/hyperf.php gen:resource User

Fatal error: Uncaught Roave\BetterReflection\Reflector\Exception\IdentifierNotFound: Roave\BetterReflection\Reflection\ReflectionClass "Hyperf\HttpMessage\Server\ResponseProxyTrait" could not be found in the located source in /Users/guo/PhpstormProjects/flower_apk_api/vendor/roave/better-reflection/src/Reflector/Exception/IdentifierNotFound.php:30
Stack trace:
#0 /Users/guo/PhpstormProjects/flower_apk_api/vendor/roave/better-reflection/src/Reflector/ClassReflector.php(40): Roave\BetterReflection\Reflector\Exception\IdentifierNotFound::fromIdentifier(Object(Roave\BetterReflection\Identifier\Identifier))
#1 /Users/guo/PhpstormProjects/flower_apk_api/vendor/roave/better-reflection/src/Reflection/ReflectionClass.php(977): Roave\BetterReflection\Reflector\ClassReflector->reflect('Hyperf\\HttpMess...')
#2 /Users/guo/PhpstormProjects/flower_apk_api/vendor/roave/better-reflection/src/Reflection/ReflectionClass.php(952): Roave\BetterReflection\Reflection\ReflectionClass->reflectClassForNamedNode(Object(PhpParser\Node\Name\FullyQua in /Users/guo/PhpstormProjects/flower_apk_api/vendor/roave/better-reflection/src/Reflector/Exception/IdentifierNotFound.php on line 30
```
请问下这是什么原因啊

**Comment by limingxinleo** [comment]
http-message 组件也用 dev-master
