### ISSUE TITLE
API 资源构造器支持swoole么？

### ISSUE THREAD

**Issue by xiaofeiphp** [hyperf/resource#2]
如果走postman能出来不会报错。把toResponse换成toArray也可以 。 但是走swoole  toResponse就会报错

![1603076871451](https://user-images.githubusercontent.com/30361735/96397121-5e361c00-11fb-11eb-82a6-52032dd6547d.jpg)
![image](https://user-images.githubusercontent.com/30361735/96405594-356c5180-1210-11eb-8b53-7a9c26b4d86c.png)

**Comment by limingxinleo** [comment]
报错信息贴上来

**Comment by xiaofeiphp** [comment]
![Uploading image.png…]()

**Comment by xiaofeiphp** [comment]
![Uploading image.png…]()

**Comment by xiaofeiphp** [comment]
![image](https://user-images.githubusercontent.com/30361735/96405641-53d24d00-1210-11eb-836d-0ef585caab2b.png)

**Comment by xiaofeiphp** [comment]
```
#0 /Users/wuxiaofei/PhpstormProjects/php/flower_apk_api/vendor/hyperf/resource/src/Response/PaginatedResponse.php(23): Hyperf\Resource\Response\Response->response()
#1 /Users/wuxiaofei/PhpstormProjects/php/flower_apk_api/vendor/hyperf/resource/src/Json/ResourceCollection.php(74): Hyperf\Resource\Response\PaginatedResponse->toResponse()
#2 /Users/wuxiaofei/PhpstormProjects/php/flower_apk_api/app/Controller/TestController.php(25): Hyperf\Resource\Json\ResourceCollection->toResponse()
#3 /Users/wuxiaofei/PhpstormProjects/php/flower_apk_api/vendor/hyperf/socketio-server/src/SocketIO.php(295): App\Controller\TestController->test(Object(Hyperf\SocketIOServer\Socket), Array)
#4 /Users/wuxiaofei/PhpstormProjects/php/flower_apk_api/vendor/hyper in /Users/wuxiaofei/PhpstormProjects/php/flower_apk_api/vendor/hyperf/resource/src/Response/Response.php on line 108
[2020-10-19 11:37:31 *28425.1]  ERROR   php_swoole_server_rshutdown (ERRNO 503): Fatal error: Uncaught TypeError: Return value of Hyperf\Resource\Response\Response::response() must implement interface Psr\Http\Message\ResponseInterface, null returned in /Users/wuxiaofei/PhpstormProjects/php/flower_apk_api/vendor/hyperf/resource/src/Response/Response.php:108
Stack trace:
```

**Comment by xiaofeiphp** [comment]
> 报错信息贴上来

传上去了
